name: Suggestion
description: Submit a suggestion to improve this mod.
labels: [suggestion]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your suggestion here."
    validations:
      required: true
